apurvalodha23.md

apurvalodha23.md

---

contributors-list/harshit-paneri.md
contributors-list/hsoni6954.md

Reverts FOSS-Tech/Git-Github-Session#51

Revert "hsoni6954.md"

---

contributors-list/divyashaktipal.md

addeddivyashaktpal.md

---

contributors-list/Mitesh.md

add_Mitvesh

---

contributors-list/RIYAJAIN21.md

added_name

---

contributors-list/priyanshuarora595.md

added a new file ( priyanshuarora595.md ) in the contributors list

added priyanshuarora595.md

---

contributors-list/avani07joshi.md

added a new contributor avani07joshi

added avani07joshi.md

---

kanishka-parmar.md

added a new contributor kanishka-parmar

added kanishka-parmar.md

---

contributors-list/Pushkar-Gameti.md

add_Pushkar-Gameti

---

kanishka-parmar.md

You need to add the file in the contributors-list folder , not in the main directory.

Revert "added kanishka-parmar.md"

---

contributors-list/Nisha-lohar.md

added a new contributor Nisha-lohar

added Nisha-lohar.md

---

contributors-list/Vyomji.md

changed the name Vyomji.md

---

contributors-list/jaydeepdangi.md

added a new contributor jadeepdangi

added jaydeepdangi.md

---

contributors-list/AasthaDakhera.md

added a new contributor AasthaDakhera

added AasthaDakhera.md

---

contributors-list/Yashgoswami14.md

added a new contributor Yashgoswami14.md

added Yashgoswami14.md

---

contributors-list/manas2003.md

added a new contributor manas2003

added manas2003.md

---

contributors-list/vaibhavsoni18.md

add new contributer vaibhavsoni18.md

added vaibhavsoni18.md

---

contributors-list/lalita2206.md

added a new contributor lalita2206

added lalita2206.md

---

contributors-list/divyanshu212

add_divyanshu212

---

contributors-list/Lakshya-bhavsar.md

add  a new contributor Lakshya-bhavsar

added Lakshya-bhavsar

---

contributors-list/pranjal1902.md

added a new contributor pranjal1902

added_pranjal1902.md

---

contributors-list/tanishakumawat.md

added a new contributor tanishakumawat

added tanishakumawat.md

---

contributors-list/Rupalsoni123.md

added Rupalsoni123.md

---

contributors-list/nehal1123.md

added a new contributor nehal1123

added nehal1123.md
